version: '3'
services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: VaultWarden
    restart: always
    #environment:
    #  - WEBSOCKET_ENABLED=false  # WebSockets will not work with this type of tunnel. If you have a solution, pull requests are welcome!
    #  - SIGNUPS_ALLOWED=false
    #  - DOMAIN=https://bitwarden.example.com
    #  - SMTP_HOST=<smtp_host>
    #  - SMTP_FROM=<sender_address>
    #  - SMTP_PORT=587
    #  - SMTP_SSL=true
    #  - SMTP_USERNAME=<sender_username>
    #  - SMTP_PASSWORD=<sender_password>
    #  - ADMIN_TOKEN=<admin token>
    volumes:
      - ./vw-data:/data 
    
    # The following port configuration doesn't need to be uncommented and exposed if tunnel is working. 
    # When commented out, it'll be exposed on port 80 to cloudflared, but not to the outside world. 
    # Uncomment this to expose it via HTTP.
    #ports:    
    #  - 80:80

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: VaultWarden_CloudFlare
    restart: always
    command: "tunnel --no-autoupdate run --token <token here>"
    # the token is created with ZeroTrust > Tunnels and specific to this subdomain
    volumes:
      - ./cloudflared:/etc/cloudflared
    depends_on:
      - vaultwarden
